"""changed to author_id

Revision ID: 75afce035b90
Revises: 039d58b45ac4
Create Date: 2026-06-10 19:37:15.416963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75afce035b90'
down_revision: Union[str, Sequence[str], None] = '039d58b45ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
