"""deleted revoke column

Revision ID: 8baae8e87005
Revises: ec8e61247f0b
Create Date: 2026-06-11 21:52:00.731403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8baae8e87005'
down_revision: Union[str, Sequence[str], None] = 'ec8e61247f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
